name: Run Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: oracle
      - name: Run tests
        run: |
          pwd
          cd 
          mvn test -D test=WebRequestTest echo output.txt
